set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
set_property PACKAGE_PIN L16 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
set_property PACKAGE_PIN T16 [get_ports {dip_switches_4bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_switches_4bits_tri_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_switches_4bits_tri_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_switches_4bits_tri_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dip_switches_4bits_tri_i[0]}]
set_property PACKAGE_PIN R3 [get_ports {dip_switches_4bits_tri_i[1]}]
set_property PACKAGE_PIN P15 [get_ports {dip_switches_4bits_tri_i[0]}]
set_property PACKAGE_PIN G15 [get_ports {dip_switches_4bits_tri_i[3]}]
set_property PACKAGE_PIN A18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property PACKAGE_PIN L16 [get_ports clk_125MHz]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4bits_tri_o[0]}]
set_property PACKAGE_PIN A17 [get_ports {led_4bits_tri_o[3]}]
set_property PACKAGE_PIN G14 [get_ports {led_4bits_tri_o[2]}]
set_property PACKAGE_PIN M15 [get_ports {led_4bits_tri_o[1]}]
set_property PACKAGE_PIN M14 [get_ports {led_4bits_tri_o[0]}]
set_property PACKAGE_PIN T20 [get_ports spi_clk]
set_property PACKAGE_PIN U20 [get_ports spi_cs]
set_property PACKAGE_PIN V20 [get_ports spi_miso]
set_property PACKAGE_PIN W20 [get_ports spi_mosi]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property PACKAGE_PIN Y18 [get_ports uart_rxd]
set_property PACKAGE_PIN N1 [get_ports uart_txd]

set_property IOSTANDARD LVCMOS33 [get_ports eth_rst]
set_property PACKAGE_PIN E17 [get_ports eth_rst]

set_property PACKAGE_PIN R2 [get_ports {dip_switches_4bits_tri_i[3]}]
set_property PACKAGE_PIN T2 [get_ports {dip_switches_4bits_tri_i[2]}]
set_property PACKAGE_PIN T3 [get_ports {dip_switches_4bits_tri_i[0]}]
set_property PACKAGE_PIN J1 [get_ports spi_clk]
set_property PACKAGE_PIN K2 [get_ports spi_cs]
set_property PACKAGE_PIN L1 [get_ports spi_miso]
set_property PACKAGE_PIN L2 [get_ports spi_mosi]
set_property PACKAGE_PIN N2 [get_ports uart_rxd]
set_property PACKAGE_PIN C16 [get_ports {led_4bits_tri_o[2]}]
set_property PACKAGE_PIN B16 [get_ports {led_4bits_tri_o[1]}]
set_property PACKAGE_PIN B17 [get_ports {led_4bits_tri_o[0]}]

set_property PACKAGE_PIN L17 [get_ports clk_100MHz]
