set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
set_property PACKAGE_PIN A18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property PACKAGE_PIN N1 [get_ports uart_txd]

set_property PACKAGE_PIN J1 [get_ports spi_clk]
set_property PACKAGE_PIN K2 [get_ports spi_cs]
set_property PACKAGE_PIN L1 [get_ports spi_miso]
set_property PACKAGE_PIN L2 [get_ports spi_mosi]
set_property PACKAGE_PIN N2 [get_ports uart_rxd]

set_property PACKAGE_PIN C16 [get_ports {led_2bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataA[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataA[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataA[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataA[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataA[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataA[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataA[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataA[0]}]
set_property PACKAGE_PIN T1 [get_ports index]
set_property PACKAGE_PIN V2 [get_ports quadA]
set_property PACKAGE_PIN W2 [get_ports quadB]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataB[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataB[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataB[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataB[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataB[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataB[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataB[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_dataB[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sck[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sck[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sck[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sck[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sck[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sck[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sck[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_sck[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports index]
set_property IOSTANDARD LVCMOS33 [get_ports quadA]
set_property IOSTANDARD LVCMOS33 [get_ports quadB]
set_property IOSTANDARD LVCMOS33 [get_ports {led_2bits_tri_o[1]}]





set_property PACKAGE_PIN U7 [get_ports {dac_dataA[2]}]
set_property PACKAGE_PIN W7 [get_ports {dac_dataA[1]}]
set_property PACKAGE_PIN V8 [get_ports {dac_dataA[0]}]

connect_debug_port u_ila_1/clk [get_nets [list u_ila_1_clk_out1]]

create_clock -period 83.333 -name clk_12MHz -waveform {0.000 41.667} [get_ports clk_12MHz]
create_generated_clock -name {GEN_INSTANCES[0].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[0].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/opt_has_pipe.i_pipe[3].pipe_reg[3][0]/Q}]
create_generated_clock -name {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tvalid} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tvalid_reg/Q}]
create_generated_clock -name {GEN_INSTANCES[1].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[1].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/opt_has_pipe.i_pipe[3].pipe_reg[3][0]/Q}]
create_generated_clock -name {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tvalid} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tvalid_reg/Q}]
create_generated_clock -name {GEN_INSTANCES[2].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[2].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/opt_has_pipe.i_pipe[3].pipe_reg[3][0]/Q}]
create_generated_clock -name {GEN_INSTANCES[2].sin_cos_inst/s_axis_phase_tvalid} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[2].sin_cos_inst/s_axis_phase_tvalid_reg/Q}]
create_generated_clock -name {GEN_INSTANCES[3].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[3].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/opt_has_pipe.i_pipe[3].pipe_reg[3][0]/Q}]
create_generated_clock -name {GEN_INSTANCES[3].sin_cos_inst/s_axis_phase_tvalid} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[3].sin_cos_inst/s_axis_phase_tvalid_reg/Q}]
create_generated_clock -name {GEN_INSTANCES[4].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[4].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/opt_has_pipe.i_pipe[3].pipe_reg[3][0]/Q}]
create_generated_clock -name {GEN_INSTANCES[4].sin_cos_inst/s_axis_phase_tvalid} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[4].sin_cos_inst/s_axis_phase_tvalid_reg/Q}]
create_generated_clock -name {GEN_INSTANCES[5].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[5].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/opt_has_pipe.i_pipe[3].pipe_reg[3][0]/Q}]
create_generated_clock -name {GEN_INSTANCES[5].sin_cos_inst/s_axis_phase_tvalid} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[5].sin_cos_inst/s_axis_phase_tvalid_reg/Q}]
create_generated_clock -name {GEN_INSTANCES[6].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[6].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/opt_has_pipe.i_pipe[3].pipe_reg[3][0]/Q}]
create_generated_clock -name {GEN_INSTANCES[6].sin_cos_inst/s_axis_phase_tvalid} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[6].sin_cos_inst/s_axis_phase_tvalid_reg/Q}]
create_generated_clock -name {GEN_INSTANCES[7].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[7].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/opt_has_pipe.i_pipe[3].pipe_reg[3][0]/Q}]
create_generated_clock -name {GEN_INSTANCES[7].sin_cos_inst/s_axis_phase_tvalid} -source [get_pins mc_wrapper_i/mc_design_i/clk_wiz/inst/mmcm_adv_inst/CLKOUT4] -divide_by 1 [get_pins {GEN_INSTANCES[7].sin_cos_inst/s_axis_phase_tvalid_reg/Q}]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[0].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tvalid}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[1].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tvalid}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[2].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[2].sin_cos_inst/s_axis_phase_tvalid}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[3].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[3].sin_cos_inst/s_axis_phase_tvalid}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[4].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[4].sin_cos_inst/s_axis_phase_tvalid}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[5].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[5].sin_cos_inst/s_axis_phase_tvalid}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[6].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[6].sin_cos_inst/s_axis_phase_tvalid}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[7].sin_cos_inst/dds_ins/U0/i_synth/i_has_nd_rdy_pipe.valid_phase_read_del/rdy_stream_i}] -group [get_clocks clk_out5_clk_wiz_0]
set_clock_groups -asynchronous -group [get_clocks {GEN_INSTANCES[7].sin_cos_inst/s_axis_phase_tvalid}] -group [get_clocks clk_out5_clk_wiz_0]

set_property PACKAGE_PIN P1 [get_ports {dac_dataA[3]}]
set_property PACKAGE_PIN P3 [get_ports {dac_dataA[4]}]
set_property PACKAGE_PIN N3 [get_ports {dac_dataA[5]}]
set_property PACKAGE_PIN M1 [get_ports {dac_dataA[6]}]
set_property PACKAGE_PIN M2 [get_ports {dac_dataA[7]}]
set_property PACKAGE_PIN V7 [get_ports {dac_dataB[0]}]
set_property PACKAGE_PIN V5 [get_ports {dac_dataB[1]}]
set_property PACKAGE_PIN U5 [get_ports {dac_dataB[2]}]
set_property PACKAGE_PIN U8 [get_ports {dac_dataB[3]}]
set_property PACKAGE_PIN W6 [get_ports {dac_dataB[4]}]
set_property PACKAGE_PIN W4 [get_ports {dac_dataB[5]}]
set_property PACKAGE_PIN W5 [get_ports {dac_dataB[6]}]
set_property PACKAGE_PIN V4 [get_ports {dac_dataB[7]}]
set_property PACKAGE_PIN U2 [get_ports {dac_sck[1]}]
set_property PACKAGE_PIN U4 [get_ports {dac_sck[0]}]
set_property PACKAGE_PIN U3 [get_ports {dac_sck[2]}]
set_property PACKAGE_PIN W3 [get_ports {dac_sck[3]}]
set_property PACKAGE_PIN V3 [get_ports {dac_sck[4]}]
set_property PACKAGE_PIN U1 [get_ports {dac_sck[5]}]
set_property PACKAGE_PIN T3 [get_ports {dac_sck[6]}]
set_property PACKAGE_PIN R3 [get_ports {dac_sck[7]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list mc_wrapper_i/mc_design_i/clk_wiz/inst/clk_out5]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[0]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[1]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[2]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[3]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[4]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[5]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[6]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[7]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[8]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[9]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[10]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[11]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[12]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[13]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[14]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[15]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[16]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[17]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[18]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[19]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[20]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[21]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[22]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[23]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[24]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[25]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[26]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[27]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[28]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[29]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[30]} {GEN_INSTANCES[1].sin_cos_inst/s_axis_phase_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 20 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[0]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[1]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[2]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[3]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[4]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[5]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[6]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[7]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[8]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[9]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[16]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[17]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[18]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[19]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[20]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[21]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[22]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[23]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[24]} {GEN_INSTANCES[0].sin_cos_inst/m_axis_data_tdata[25]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[0]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[1]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[2]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[3]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[4]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[5]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[6]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[7]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[8]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[9]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[10]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[11]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[12]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[13]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[14]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[15]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[16]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[17]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[18]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[19]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[20]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[21]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[22]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[23]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[24]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[25]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[26]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[27]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[28]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[29]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[30]} {GEN_INSTANCES[0].sin_cos_inst/s_axis_phase_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 20 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[0]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[1]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[2]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[3]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[4]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[5]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[6]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[7]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[8]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[9]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[16]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[17]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[18]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[19]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[20]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[21]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[22]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[23]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[24]} {GEN_INSTANCES[1].sin_cos_inst/m_axis_data_tdata[25]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list mc_wrapper_i/mc_design_i/clk_wiz/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {sin_cos_ch1_phase_inc_threshold[0]} {sin_cos_ch1_phase_inc_threshold[1]} {sin_cos_ch1_phase_inc_threshold[2]} {sin_cos_ch1_phase_inc_threshold[3]} {sin_cos_ch1_phase_inc_threshold[4]} {sin_cos_ch1_phase_inc_threshold[5]} {sin_cos_ch1_phase_inc_threshold[6]} {sin_cos_ch1_phase_inc_threshold[7]} {sin_cos_ch1_phase_inc_threshold[8]} {sin_cos_ch1_phase_inc_threshold[9]} {sin_cos_ch1_phase_inc_threshold[10]} {sin_cos_ch1_phase_inc_threshold[11]} {sin_cos_ch1_phase_inc_threshold[12]} {sin_cos_ch1_phase_inc_threshold[13]} {sin_cos_ch1_phase_inc_threshold[14]} {sin_cos_ch1_phase_inc_threshold[15]} {sin_cos_ch1_phase_inc_threshold[16]} {sin_cos_ch1_phase_inc_threshold[17]} {sin_cos_ch1_phase_inc_threshold[18]} {sin_cos_ch1_phase_inc_threshold[19]} {sin_cos_ch1_phase_inc_threshold[20]} {sin_cos_ch1_phase_inc_threshold[21]} {sin_cos_ch1_phase_inc_threshold[22]} {sin_cos_ch1_phase_inc_threshold[23]} {sin_cos_ch1_phase_inc_threshold[24]} {sin_cos_ch1_phase_inc_threshold[25]} {sin_cos_ch1_phase_inc_threshold[26]} {sin_cos_ch1_phase_inc_threshold[27]} {sin_cos_ch1_phase_inc_threshold[28]} {sin_cos_ch1_phase_inc_threshold[29]} {sin_cos_ch1_phase_inc_threshold[30]} {sin_cos_ch1_phase_inc_threshold[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 32 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {sin_cos_ch0_phase_inc_delta[0]} {sin_cos_ch0_phase_inc_delta[1]} {sin_cos_ch0_phase_inc_delta[2]} {sin_cos_ch0_phase_inc_delta[3]} {sin_cos_ch0_phase_inc_delta[4]} {sin_cos_ch0_phase_inc_delta[5]} {sin_cos_ch0_phase_inc_delta[6]} {sin_cos_ch0_phase_inc_delta[7]} {sin_cos_ch0_phase_inc_delta[8]} {sin_cos_ch0_phase_inc_delta[9]} {sin_cos_ch0_phase_inc_delta[10]} {sin_cos_ch0_phase_inc_delta[11]} {sin_cos_ch0_phase_inc_delta[12]} {sin_cos_ch0_phase_inc_delta[13]} {sin_cos_ch0_phase_inc_delta[14]} {sin_cos_ch0_phase_inc_delta[15]} {sin_cos_ch0_phase_inc_delta[16]} {sin_cos_ch0_phase_inc_delta[17]} {sin_cos_ch0_phase_inc_delta[18]} {sin_cos_ch0_phase_inc_delta[19]} {sin_cos_ch0_phase_inc_delta[20]} {sin_cos_ch0_phase_inc_delta[21]} {sin_cos_ch0_phase_inc_delta[22]} {sin_cos_ch0_phase_inc_delta[23]} {sin_cos_ch0_phase_inc_delta[24]} {sin_cos_ch0_phase_inc_delta[25]} {sin_cos_ch0_phase_inc_delta[26]} {sin_cos_ch0_phase_inc_delta[27]} {sin_cos_ch0_phase_inc_delta[28]} {sin_cos_ch0_phase_inc_delta[29]} {sin_cos_ch0_phase_inc_delta[30]} {sin_cos_ch0_phase_inc_delta[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 32 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {sin_cos_ch0_phase_inc_threshold[0]} {sin_cos_ch0_phase_inc_threshold[1]} {sin_cos_ch0_phase_inc_threshold[2]} {sin_cos_ch0_phase_inc_threshold[3]} {sin_cos_ch0_phase_inc_threshold[4]} {sin_cos_ch0_phase_inc_threshold[5]} {sin_cos_ch0_phase_inc_threshold[6]} {sin_cos_ch0_phase_inc_threshold[7]} {sin_cos_ch0_phase_inc_threshold[8]} {sin_cos_ch0_phase_inc_threshold[9]} {sin_cos_ch0_phase_inc_threshold[10]} {sin_cos_ch0_phase_inc_threshold[11]} {sin_cos_ch0_phase_inc_threshold[12]} {sin_cos_ch0_phase_inc_threshold[13]} {sin_cos_ch0_phase_inc_threshold[14]} {sin_cos_ch0_phase_inc_threshold[15]} {sin_cos_ch0_phase_inc_threshold[16]} {sin_cos_ch0_phase_inc_threshold[17]} {sin_cos_ch0_phase_inc_threshold[18]} {sin_cos_ch0_phase_inc_threshold[19]} {sin_cos_ch0_phase_inc_threshold[20]} {sin_cos_ch0_phase_inc_threshold[21]} {sin_cos_ch0_phase_inc_threshold[22]} {sin_cos_ch0_phase_inc_threshold[23]} {sin_cos_ch0_phase_inc_threshold[24]} {sin_cos_ch0_phase_inc_threshold[25]} {sin_cos_ch0_phase_inc_threshold[26]} {sin_cos_ch0_phase_inc_threshold[27]} {sin_cos_ch0_phase_inc_threshold[28]} {sin_cos_ch0_phase_inc_threshold[29]} {sin_cos_ch0_phase_inc_threshold[30]} {sin_cos_ch0_phase_inc_threshold[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 32 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {sin_cos_ch1_phase_inc_delta[0]} {sin_cos_ch1_phase_inc_delta[1]} {sin_cos_ch1_phase_inc_delta[2]} {sin_cos_ch1_phase_inc_delta[3]} {sin_cos_ch1_phase_inc_delta[4]} {sin_cos_ch1_phase_inc_delta[5]} {sin_cos_ch1_phase_inc_delta[6]} {sin_cos_ch1_phase_inc_delta[7]} {sin_cos_ch1_phase_inc_delta[8]} {sin_cos_ch1_phase_inc_delta[9]} {sin_cos_ch1_phase_inc_delta[10]} {sin_cos_ch1_phase_inc_delta[11]} {sin_cos_ch1_phase_inc_delta[12]} {sin_cos_ch1_phase_inc_delta[13]} {sin_cos_ch1_phase_inc_delta[14]} {sin_cos_ch1_phase_inc_delta[15]} {sin_cos_ch1_phase_inc_delta[16]} {sin_cos_ch1_phase_inc_delta[17]} {sin_cos_ch1_phase_inc_delta[18]} {sin_cos_ch1_phase_inc_delta[19]} {sin_cos_ch1_phase_inc_delta[20]} {sin_cos_ch1_phase_inc_delta[21]} {sin_cos_ch1_phase_inc_delta[22]} {sin_cos_ch1_phase_inc_delta[23]} {sin_cos_ch1_phase_inc_delta[24]} {sin_cos_ch1_phase_inc_delta[25]} {sin_cos_ch1_phase_inc_delta[26]} {sin_cos_ch1_phase_inc_delta[27]} {sin_cos_ch1_phase_inc_delta[28]} {sin_cos_ch1_phase_inc_delta[29]} {sin_cos_ch1_phase_inc_delta[30]} {sin_cos_ch1_phase_inc_delta[31]}]]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sck]
set_property PACKAGE_PIN L3 [get_ports dac_sck]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_12MHz_IBUF]
