set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports spi_mosi]
set_property PACKAGE_PIN A18 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property PACKAGE_PIN N1 [get_ports uart_txd]

set_property PACKAGE_PIN J1 [get_ports spi_clk]
set_property PACKAGE_PIN K2 [get_ports spi_cs]
set_property PACKAGE_PIN L1 [get_ports spi_miso]
set_property PACKAGE_PIN L2 [get_ports spi_mosi]
set_property PACKAGE_PIN N2 [get_ports uart_rxd]

set_property PACKAGE_PIN C16 [get_ports {led_2bits_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN T2 [get_ports dac_dataA]
set_property IOSTANDARD LVCMOS33 [get_ports dac_dataA]
set_property PACKAGE_PIN R3 [get_ports dac_dataB]
set_property PACKAGE_PIN T3 [get_ports dac_sck]
set_property PACKAGE_PIN T1 [get_ports index]
set_property PACKAGE_PIN V2 [get_ports quadA]
set_property PACKAGE_PIN W2 [get_ports quadB]
set_property IOSTANDARD LVCMOS33 [get_ports dac_dataB]
set_property IOSTANDARD LVCMOS33 [get_ports dac_sck]
set_property IOSTANDARD LVCMOS33 [get_ports index]
set_property IOSTANDARD LVCMOS33 [get_ports quadA]
set_property IOSTANDARD LVCMOS33 [get_ports quadB]
set_property IOSTANDARD LVCMOS33 [get_ports {led_2bits_tri_o[1]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list mc_wrapper_i/mc_design_i/clk_wiz/inst/clk_out5]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 10 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {sin_cos_inst/dac1A_data[2]} {sin_cos_inst/dac1A_data[3]} {sin_cos_inst/dac1A_data[4]} {sin_cos_inst/dac1A_data[5]} {sin_cos_inst/dac1A_data[6]} {sin_cos_inst/dac1A_data[7]} {sin_cos_inst/dac1A_data[8]} {sin_cos_inst/dac1A_data[9]} {sin_cos_inst/dac1A_data[10]} {sin_cos_inst/dac1A_data[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 20 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {sin_cos_inst/m_axis_data_tdata[0]} {sin_cos_inst/m_axis_data_tdata[1]} {sin_cos_inst/m_axis_data_tdata[2]} {sin_cos_inst/m_axis_data_tdata[3]} {sin_cos_inst/m_axis_data_tdata[4]} {sin_cos_inst/m_axis_data_tdata[5]} {sin_cos_inst/m_axis_data_tdata[6]} {sin_cos_inst/m_axis_data_tdata[7]} {sin_cos_inst/m_axis_data_tdata[8]} {sin_cos_inst/m_axis_data_tdata[9]} {sin_cos_inst/m_axis_data_tdata[16]} {sin_cos_inst/m_axis_data_tdata[17]} {sin_cos_inst/m_axis_data_tdata[18]} {sin_cos_inst/m_axis_data_tdata[19]} {sin_cos_inst/m_axis_data_tdata[20]} {sin_cos_inst/m_axis_data_tdata[21]} {sin_cos_inst/m_axis_data_tdata[22]} {sin_cos_inst/m_axis_data_tdata[23]} {sin_cos_inst/m_axis_data_tdata[24]} {sin_cos_inst/m_axis_data_tdata[25]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {sin_cos_inst/s_axis_phase_tdata[0]} {sin_cos_inst/s_axis_phase_tdata[1]} {sin_cos_inst/s_axis_phase_tdata[2]} {sin_cos_inst/s_axis_phase_tdata[3]} {sin_cos_inst/s_axis_phase_tdata[4]} {sin_cos_inst/s_axis_phase_tdata[5]} {sin_cos_inst/s_axis_phase_tdata[6]} {sin_cos_inst/s_axis_phase_tdata[7]} {sin_cos_inst/s_axis_phase_tdata[8]} {sin_cos_inst/s_axis_phase_tdata[9]} {sin_cos_inst/s_axis_phase_tdata[10]} {sin_cos_inst/s_axis_phase_tdata[11]} {sin_cos_inst/s_axis_phase_tdata[12]} {sin_cos_inst/s_axis_phase_tdata[13]} {sin_cos_inst/s_axis_phase_tdata[14]} {sin_cos_inst/s_axis_phase_tdata[15]} {sin_cos_inst/s_axis_phase_tdata[16]} {sin_cos_inst/s_axis_phase_tdata[17]} {sin_cos_inst/s_axis_phase_tdata[18]} {sin_cos_inst/s_axis_phase_tdata[19]} {sin_cos_inst/s_axis_phase_tdata[20]} {sin_cos_inst/s_axis_phase_tdata[21]} {sin_cos_inst/s_axis_phase_tdata[22]} {sin_cos_inst/s_axis_phase_tdata[23]} {sin_cos_inst/s_axis_phase_tdata[24]} {sin_cos_inst/s_axis_phase_tdata[25]} {sin_cos_inst/s_axis_phase_tdata[26]} {sin_cos_inst/s_axis_phase_tdata[27]} {sin_cos_inst/s_axis_phase_tdata[28]} {sin_cos_inst/s_axis_phase_tdata[29]} {sin_cos_inst/s_axis_phase_tdata[30]} {sin_cos_inst/s_axis_phase_tdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 10 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {sin_cos_inst/dac1B_data[2]} {sin_cos_inst/dac1B_data[3]} {sin_cos_inst/dac1B_data[4]} {sin_cos_inst/dac1B_data[5]} {sin_cos_inst/dac1B_data[6]} {sin_cos_inst/dac1B_data[7]} {sin_cos_inst/dac1B_data[8]} {sin_cos_inst/dac1B_data[9]} {sin_cos_inst/dac1B_data[10]} {sin_cos_inst/dac1B_data[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list sin_cos_inst/sync_flag]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list sin_cos_inst/m_axis_data_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list sin_cos_inst/s_axis_phase_tvalid]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_wiz_i/inst/clk_out5]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 1 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list sin_cos_inst/tlv5637_ip/sync]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_1mhz]
