domain_path: C:\Users\piotr\Dropbox\Projects2\FPGA\motion_controller\FW\vitis\platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
